/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Drawer: typeof import('@/components/MyDrawer/MyDrawer.vue')['default']
    DrawerButton: typeof import('./src/components/Drawer/DrawerButton.vue')['default']
    DrawerContent: typeof import('./src/components/Drawer/DrawerContent.vue')['default']
    DrawerHandle: typeof import('./src/components/Drawer/DrawerHandle.vue')['default']
    DynamicRows: typeof import('./src/components/Table/DynamicRows.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyDrawer: typeof import('./src/components/Drawer/MyDrawer.vue')['default']
    MyTable: typeof import('./src/components/Table/MyTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusRow: typeof import('./src/components/Table/StatusRow.vue')['default']
  }
}
